---
- name: DellEMC PowerEdge - Making contact with DellEMC PowerEdge
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
          idrac_ip: "10.0.0.89"
          idrac_user: "root"
          idrac_password: "r0gerwilc0"
  tasks:
        - name: Poll iDRAC lifecycle status
          dellemc.openmanage.idrac_lifecycle_controller_status_info:
                  validate_certs: False        # in production, turn this to True
                  idrac_ip: "{{ idrac_ip }}"
                  idrac_user: "{{ idrac_user }}"
                  idrac_password: "{{ idrac_password }}"
          register: results

        - name: Display the information collected on the Lifecycle Controller
          debug:
                  var: results
